# Fase 01 (Builder)
FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY index.js ./

# Fase 02 (Runner)
FROM node:18-alpine AS runner

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY --from=builder /usr/src/app/index.js .

EXPOSE 3000
CMD [ "node", "index.js" ]